using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using MdloDtos;
using MdloDtos.DTO;

namespace AccsoDtos.Mappings
{
    /// <summary>
    /// Daniel Lopez
    /// Mapper para la tabla consectivo.
    /// </summary>
    public class MappingProfile:Profile
    {
        public MappingProfile()
        {

            CreateMap<Consecutivo, ConsecutivoDTO>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom((src, _) => src.CoRowid))
                .ForMember(dest => dest.CodigoCompania, opt => opt.MapFrom((src, _) => src.CoCdgoCiaNavigation?.CiaCdgo))
                .ForMember(dest => dest.NombreCompania, opt => opt.MapFrom((src, _) => src.CoCdgoCiaNavigation?.CiaNmbre))
                .ForMember(dest => dest.Codigo, opt => opt.MapFrom((src, _) => src.CoCdgo))
                .ForMember(dest => dest.Nombre, opt => opt.MapFrom((src, _) => src.CoNmbre))
                .ForMember(dest => dest.Contador, opt => opt.MapFrom((src, _) => src.CoCntdor));

            CreateMap<Parametro, ParametroDTO>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom((src, _) => src.PaId))
                .ForMember(dest => dest.Empresa, opt => opt.MapFrom((src, _) => src.PaEmprsa))
                .ForMember(dest => dest.DiasVigenciaClaveInternos, opt => opt.MapFrom((src, _) => src.PaDiasVgnciaClveIntrnos))
                .ForMember(dest => dest.DiasVigenciaClaveExternos, opt => opt.MapFrom((src, _) => src.PaDiasVgnciaClveExtrnos))
                .ForMember(dest => dest.ClavesAnteriores, opt => opt.MapFrom((src, _) => src.PaClvesAntrres))
                .ForMember(dest => dest.DiasExternos, opt => opt.MapFrom((src, _) => src.PaDiasInctvcionExtrnos))
                .ForMember(dest => dest.ServidorCorreo, opt => opt.MapFrom((src, _) => src.PaCrreoSrvdor))
                .ForMember(dest => dest.CorreoUsuario, opt => opt.MapFrom((src, _) => src.PaCrreoUsrio))
                .ForMember(dest => dest.CorreoClave, opt => opt.MapFrom((src, _) => src.PaCrreoClve))
                .ForMember(dest => dest.CorreoPuerto, opt => opt.MapFrom((src, _) => src.PaCrreoPrto))
                .ForMember(dest => dest.CorreoConexionSegura, opt => opt.MapFrom((src, _) => src.PaCrreoCnxionSgra))
                .ForMember(dest => dest.URL, opt => opt.MapFrom((src, _) => src.PaUrlPrtalLgstco))
                .ForMember(dest => dest.RutaNas, opt => opt.MapFrom((src, _) => src.PaNasRuta))
                .ForMember(dest => dest.UsuarioNas, opt => opt.MapFrom((src, _) => src.PaNasUsuario))
                .ForMember(dest => dest.ClaveNas, opt => opt.MapFrom((src, _) => src.PaNasClave))
                .ForMember(dest => dest.PuertoNas, opt => opt.MapFrom((src, _) => src.PaNasPuerto))
                .ForMember(dest => dest.SaldoBajoDeposito, opt => opt.MapFrom((src, _) => src.PaSldoBjoDpsto))
                .ForMember(dest => dest.SaldoBajoSolicitudRetiro, opt => opt.MapFrom((src, _) => src.PaSldoBjoSlctudRtro))
                .ForMember(dest => dest.PesoMaximoCargar, opt => opt.MapFrom((src, _) => src.PaPsoMxmoACrgar))
                .ForMember(dest => dest.MinutosVigenciaReserva, opt => opt.MapFrom((src, _) => src.PaMntosVgnviaRsrva)).ReverseMap();

            CreateMap<Clasificacion, ClasificacionDTO>()
               .ForMember(dest => dest.Id, opt => opt.MapFrom((src, _) => src.ClRowid))
               .ForMember(dest => dest.Nombre, opt => opt.MapFrom((src, _) => src.ClNmbre))
               .ForMember(dest => dest.Descripcion, opt => opt.MapFrom((src, _) => src.ClDscrpcion))
               .ForMember(dest => dest.FechaCreacion, opt => opt.MapFrom((src, _) => src.ClFchaCrcion))
               .ForMember(dest => dest.CodigoUsuario, opt => opt.MapFrom((src, _) => src.ClCdgoUsrio))
               .ForMember(dest => dest.Estado, opt => opt.MapFrom((src, _) => src.ClActvo));

            CreateMap<Motonave, MotonaveDTO>()
                .ForMember(dest => dest.Codigo, opt => opt.MapFrom((src, _) => src.MoCdgo))
                .ForMember(dest => dest.Nombre, opt => opt.MapFrom((src, _) => src.MoNmbre))
                .ForMember(dest => dest.Eslra, opt => opt.MapFrom((src, _) => src.MoEslra))
                .ForMember(dest => dest.Mtrcla, opt => opt.MapFrom((src, _) => src.MoMtrcla))
                .ForMember(dest => dest.MoBndra, opt => opt.MapFrom((src, _) => src.MoBndra))
                .ForMember(dest => dest.CantidadEscotillas, opt => opt.MapFrom((src, _) => src.MoCntdadEsctllas))
                .ForMember(dest => dest.Calado, opt => opt.MapFrom((src, _) => src.MoCldo))
                .ForMember(dest => dest.SituacionPortuaria, opt => opt.MapFrom((src, _) => src.SituacionPortuaria))
                .ForMember(dest => dest.VisitaMotonaves, opt => opt.MapFrom((src, _) => src.VisitaMotonaves))
                ;

            CreateMap<Ciudad, CiudadDTO>()
                .ForMember(dest => dest.IdCiudad, opt => opt.MapFrom((src, _) => src.CiRowid))
                .ForMember(dest => dest.Codigo, opt => opt.MapFrom((src, _) => src.CiCdgo))
                .ForMember(dest => dest.Nombre, opt => opt.MapFrom((src, _) => src.CiNmbre))
                .ForMember(dest => dest.IdDepartamento, opt => opt.MapFrom((src, _) => src.CiRowidDprtmnto))
                .ForMember(dest => dest.CiRowidDprtmntoNavigation, opt => opt.MapFrom((src, _) => src.CiRowidDprtmntoNavigation))
                .ForMember(dest => dest.Ordens, opt => opt.MapFrom((src, _) => src.Ordens))
                .ForMember(dest => dest.SolicitudRetiros, opt => opt.MapFrom((src, _) => src.SolicitudRetiros));

            CreateMap<CondicionFacturacion, CondicionFacturacionDTO>()
                .ForMember(dest => dest.Codigo, opt => opt.MapFrom((src, _) => src.CfCdgo))
                .ForMember(dest => dest.Nombre, opt => opt.MapFrom((src, _) => src.CfNmbre))
                .ForMember(dest => dest.Base, opt => opt.MapFrom((src, _) => src.CfFchaBse))
                .ForMember(dest => dest.Depositos, opt => opt.MapFrom((src, _) => src.Depositos));

            CreateMap<ConfiguracionVehicular, ConfiguracionVehicularDTO>()
                .ForMember(dest => dest.IdConfiguracionVehicular, opt => opt.MapFrom((src, _) => src.CvRowid))
                .ForMember(dest => dest.Codigo, opt => opt.MapFrom((src, _) => src.CvCdgo))
                .ForMember(dest => dest.Nombre, opt => opt.MapFrom((src, _) => src.CvNmbre))
                .ForMember(dest => dest.PesoMaximo, opt => opt.MapFrom((src, _) => src.CvPsoMxmo))
                .ForMember(dest => dest.Tolerancia, opt => opt.MapFrom((src, _) => src.CvTlrncia))
                .ForMember(dest => dest.CodigoCompania, opt => opt.MapFrom((src, _) => src.CvCdgoCia))
                .ForMember(dest => dest.Estado, opt => opt.MapFrom((src, _) => src.CvActvo))
                .ForMember(dest => dest.CvCdgoCiaNavigation, opt => opt.MapFrom((src, _) => src.CvCdgoCiaNavigation))
                .ForMember(dest => dest.Ordens, opt => opt.MapFrom((src, _) => src.Ordens))
                .ForMember(dest => dest.Vehiculos, opt => opt.MapFrom((src, _) => src.Vehiculos))
                .ForMember(dest => dest.CompaniaCodigo, opt => opt.MapFrom((src, _) => src.CvCdgoCiaNavigation.CiaCdgo))
                .ForMember(dest => dest.CompaniaNombre, opt => opt.MapFrom((src, _) => src.CvCdgoCiaNavigation.CiaNmbre));

            CreateMap<Equipo, EquipoDTO>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom((src, _) => src.EqRowid))
                .ForMember(dest => dest.codigoEquipo, opt => opt.MapFrom((src, _) => src.EqCdgo))
                .ForMember(dest => dest.Nombre, opt => opt.MapFrom((src, _) => src.EqNmbre))
                .ForMember(dest => dest.Descripcion, opt => opt.MapFrom((src, _) => src.EqDscrpcion))
                .ForMember(dest => dest.FechaCreacion, opt => opt.MapFrom((src, _) => src.EqFchaCrcion))
                .ForMember(dest => dest.CodigoUsuario, opt => opt.MapFrom((src, _) => src.EqCdgoUsrio))
                .ForMember(dest => dest.Estado, opt => opt.MapFrom((src, _) => src.EqActvo));

            CreateMap<Evento, EventoDTO>()
                .ForMember(dest => dest.IdEvento, opt => opt.MapFrom((src, _) => src.EvRowid))
                .ForMember(dest => dest.Nombre, opt => opt.MapFrom((src, _) => src.EvNmbre))
                .ForMember(dest => dest.Observacion, opt => opt.MapFrom((src, _) => src.EvObsrvcion))
                .ForMember(dest => dest.FechaCreacion, opt => opt.MapFrom((src, _) => src.EvFchaCrcion))
                .ForMember(dest => dest.FechaInicio, opt => opt.MapFrom((src, _) => src.EvFchaIncio))
                .ForMember(dest => dest.FechaFin, opt => opt.MapFrom((src, _) => src.EvFchaFin))
                .ForMember(dest => dest.Escotilla, opt => opt.MapFrom((src, _) => src.EvEsctlla))
                .ForMember(dest => dest.CodigoClasificacion, opt => opt.MapFrom((src, _) => src.EvRowidClsfccion))
                .ForMember(dest => dest.CodigoResponsable, opt => opt.MapFrom((src, _) => src.EvRowidRspnsble))
                .ForMember(dest => dest.Equipo, opt => opt.MapFrom((src, _) => src.EvEqpo))
                .ForMember(dest => dest.CodigoUsuario, opt => opt.MapFrom((src, _) => src.EvCdgoUsrio))
                .ForMember(dest => dest.Estado, opt => opt.MapFrom((src, _) => src.EvActvo));

            CreateMap<Responsable, ResponsableDTO>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom((src, _) => src.ReRowid))
                .ForMember(dest => dest.Nombre, opt => opt.MapFrom((src, _) => src.ReNmbre))
                .ForMember(dest => dest.Descripcion, opt => opt.MapFrom((src, _) => src.ReDscrpcion))
                .ForMember(dest => dest.FechaCreacion, opt => opt.MapFrom((src, _) => src.ReFchaCrcion))
                .ForMember(dest => dest.CodigoUsuario, opt => opt.MapFrom((src, _) => src.ReCdgoUsrio))
                .ForMember(dest => dest.Estado, opt => opt.MapFrom((src, _) => src.ReActvo));

            CreateMap<ZonaCd, ZonaCdDTO>()
                .ForMember(dest => dest.IdZona, opt => opt.MapFrom((src, _) => src.ZcdRowid))
                .ForMember(dest => dest.Codigo, opt => opt.MapFrom((src, _) => src.ZcdCdgo))
                .ForMember(dest => dest.Nombre, opt => opt.MapFrom((src, _) => src.ZcdNmbre))
                .ForMember(dest => dest.Estado, opt => opt.MapFrom((src, _) => src.ZcdActvo))
                .ForMember(dest => dest.IdSede, opt => opt.MapFrom((src, _) => src.ZcdRowidSde))
                .ForMember(dest => dest.Bodega, opt => opt.MapFrom((src, _) => src.ZcdBdga))
                .ForMember(dest => dest.Slo, opt => opt.MapFrom((src, _) => src.ZcdSlo))
                .ForMember(dest => dest.Muelle, opt => opt.MapFrom((src, _) => src.ZcdMlle))
                .ForMember(dest => dest.Patio, opt => opt.MapFrom((src, _) => src.ZcdPtio))
                .ForMember(dest => dest.Capacidad, opt => opt.MapFrom((src, _) => src.ZcdCpcdad))
                .ForMember(dest => dest.Planta, opt => opt.MapFrom((src, _) => src.ZcdPlnta))
                .ForMember(dest => dest.SituacionPortuaria, opt => opt.MapFrom((src, _) => src.SituacionPortuaria))
                .ForMember(dest => dest.VisitaMotonaves, opt => opt.MapFrom((src, _) => src.VisitaMotonaves))
                .ForMember(dest => dest.ZcdRowidSdeNavigation, opt => opt.MapFrom((src, _) => src.ZcdRowidSdeNavigation))
                .ForMember(dest => dest.SedeRowId, opt => opt.MapFrom((src, _) => src.SedeRowId))
                .ForMember(dest => dest.SedeCodigo, opt => opt.MapFrom((src, _) => src.SedeCodigo))
                .ForMember(dest => dest.SedeNombre, opt => opt.MapFrom((src, _) => src.SedeNombre))
                .ForMember(dest => dest.EstadoHechoes, opt => opt.MapFrom((src, _) => src.EstadoHechoes))
                .ForMember(dest => dest.Ordens, opt => opt.MapFrom((src, _) => src.Ordens));

            CreateMap<Conductor, ConductorDTO>()
                .ForMember(dest => dest.Identificacion, opt => opt.MapFrom((src, _) => src.CnIdntfccion))
                .ForMember(dest => dest.Nombre, opt => opt.MapFrom((src, _) => src.CnNmbre))
                .ForMember(dest => dest.Imagen, opt => opt.MapFrom((src, _) => src.CnFeatures))
                .ForMember(dest => dest.Vehiculo, opt => opt.MapFrom((src, _) => src.CnVhclo))
                .ForMember(dest => dest.IdTransportadora, opt => opt.MapFrom((src, _) => src.CnRowidTrnsprtdra))
                .ForMember(dest => dest.FechaRegistro, opt => opt.MapFrom((src, _) => src.CnFchaRgstro))
                .ForMember(dest => dest.CodigoUsuarioEnrolo, opt => opt.MapFrom((src, _) => src.CnCdgoUsrioEnrlo))
                .ForMember(dest => dest.Movil, opt => opt.MapFrom((src, _) => src.CnMvil))
                .ForMember(dest => dest.NumeroLicencia, opt => opt.MapFrom((src, _) => src.CnNmroLcncia))
                .ForMember(dest => dest.TipoLicencia, opt => opt.MapFrom((src, _) => src.CnTpoLcncia))
                .ForMember(dest => dest.FechaVencimientoLcncia, opt => opt.MapFrom((src, _) => src.CnFchaVncmntoLcncia))
                .ForMember(dest => dest.Activo, opt => opt.MapFrom((src, _) => src.CnActvo))
                .ForMember(dest => dest.Urbano, opt => opt.MapFrom((src, _) => src.CnUrbno))
                .ForMember(dest => dest.CnRowidTrnsprtdraNavigation, opt => opt.MapFrom((src, _) => src.CnRowidTrnsprtdraNavigation));

            CreateMap<PeriodoFacturacion, PeriodoFacturacionDTO>()
              .ForMember(dest => dest.Codigo, opt => opt.MapFrom((src, _) => src.PfCdgo))
              .ForMember(dest => dest.Nombre, opt => opt.MapFrom((src, _) => src.PfNmbre))
              .ForMember(dest => dest.Dias, opt => opt.MapFrom((src, _) => src.PfDias))
              .ForMember(dest => dest.Promedio, opt => opt.MapFrom((src, _) => src.PfPrmdio))
              .ForMember(dest => dest.CodigoErp, opt => opt.MapFrom((src, _) => src.PfCdgoErp))
              .ForMember(dest => dest.Depositos, opt => opt.MapFrom((src, _) => src.Depositos));

            CreateMap<UnidadMedidum, UnidadMedidumDTO>()
             .ForMember(dest => dest.Codigo, opt => opt.MapFrom((src, _) => src.UmCdgo))
             .ForMember(dest => dest.Nombre, opt => opt.MapFrom((src, _) => src.UmNmbre))
             .ForMember(dest => dest.EsGranel, opt => opt.MapFrom((src, _) => src.UmGrnel))
             .ForMember(dest => dest.Activo, opt => opt.MapFrom((src, _) => src.UmActvo))
             .ForMember(dest => dest.SituacionPortuariaDetalles, opt => opt.MapFrom((src, _) => src.SituacionPortuariaDetalles))
             .ForMember(dest => dest.VisitaMotonaveBls, opt => opt.MapFrom((src, _) => src.VisitaMotonaveBls));

            CreateMap<TipoDocumento, TipoDocumentoDTO>()
               .ForMember(dest => dest.IdTipoDocumento, opt => opt.MapFrom((src, _) => src.TdCdgo))
               .ForMember(dest => dest.Nombre, opt => opt.MapFrom((src, _) => src.TdNmbre))
               .ForMember(dest => dest.Origen, opt => opt.MapFrom((src, _) => src.TdOrgen))
               .ForMember(dest => dest.Asignar, opt => opt.MapFrom((src, _) => src.TdNmbreAAsgnar))
               .ForMember(dest => dest.Estado, opt => opt.MapFrom((src, _) => src.TdActvo))
               .ForMember(dest => dest.EsObligatorio, opt => opt.MapFrom((src, _) => src.TdOblgtrio));

            CreateMap<TipoIdentificacion, TipoIdentificacionDTO>()
               .ForMember(dest => dest.Codigo, opt => opt.MapFrom((src, _) => src.TiCdgo))
               .ForMember(dest => dest.Nombre, opt => opt.MapFrom((src, _) => src.TiNmbre))
               .ForMember(dest => dest.Terceros, opt => opt.MapFrom((src, _) => src.Terceros));

            CreateMap<EstadoMotonave, EstadoMotonaveDTO>()
             .ForMember(dest => dest.Codigo, opt => opt.MapFrom((src, _) => src.EmCdgo))
             .ForMember(dest => dest.Nombre, opt => opt.MapFrom((src, _) => src.EmNmbre));


            CreateMap<Orden, OrdenDTO>()
                .ForMember(dest => dest.Codigo, opt => opt.MapFrom((src, _) => src.OrCdgo))
                .ForMember(dest => dest.IdTransportadora, opt => opt.MapFrom((src, _) => src.OrRowidTrnsprtdra))
                .ForMember(dest => dest.Activa, opt => opt.MapFrom((src, _) => src.OrActva))
                .ForMember(dest => dest.FechaReserva, opt => opt.MapFrom((src, _) => src.OrFchaRsrva))
                .ForMember(dest => dest.FechaRegistroReserva, opt => opt.MapFrom((src, _) => src.OrFchaRgstroRsrva))
                .ForMember(dest => dest.CodigoUsuarioReserva, opt => opt.MapFrom((src, _) => src.OrCdgoUsrioRsrva))
                .ForMember(dest => dest.Placa, opt => opt.MapFrom((src, _) => src.OrPlca))
                .ForMember(dest => dest.Remolque, opt => opt.MapFrom((src, _) => src.OrRmlque))
                .ForMember(dest => dest.Manifiesto, opt => opt.MapFrom((src, _) => src.OrMnfsto))
                .ForMember(dest => dest.Remision, opt => opt.MapFrom((src, _) => src.OrRmsion))
                .ForMember(dest => dest.IdentificacionConductor, opt => opt.MapFrom((src, _) => src.OrIdntfccionCndctor))
                .ForMember(dest => dest.Llamada, opt => opt.MapFrom((src, _) => src.OrLlmda))
                .ForMember(dest => dest.Radicada, opt => opt.MapFrom((src, _) => src.OrRdcda))
                .ForMember(dest => dest.FechaRadicacion, opt => opt.MapFrom((src, _) => src.OrFchaRdccion))
                .ForMember(dest => dest.IdDeposito, opt => opt.MapFrom((src, _) => src.OrRowidDpsto))
                .ForMember(dest => dest.IdSolicitudRetiro, opt => opt.MapFrom((src, _) => src.OrRowidSlctudRtro))
                .ForMember(dest => dest.IdConfiguracionVehicular, opt => opt.MapFrom((src, _) => src.OrRowidCnfgrcionVhclar))
                .ForMember(dest => dest.IdCiudad, opt => opt.MapFrom((src, _) => src.OrRowidCdad))
                .ForMember(dest => dest.IdZonaCargueDescargue, opt => opt.MapFrom((src, _) => src.OrRowidZnaCd))
                .ForMember(dest => dest.RadicaccionHuellaValidada, opt => opt.MapFrom((src, _) => src.OrRdccionHllaVldda))
                .ForMember(dest => dest.CodigoUsuarioRadicaccion, opt => opt.MapFrom((src, _) => src.OrCdgoUsrioRdccion))
                .ForMember(dest => dest.NumeroLLamadas, opt => opt.MapFrom((src, _) => src.OrLlmdas))
                .ForMember(dest => dest.FechaAnulacion, opt => opt.MapFrom((src, _) => src.OrFchaAnlcion))
                .ForMember(dest => dest.IdSocidad, opt => opt.MapFrom((src, _) => src.OrIdScdad))
                .ForMember(dest => dest.VigenciaTurno, opt => opt.MapFrom((src, _) => src.OrVgnciaTrno))
                .ForMember(dest => dest.TurnoValidado, opt => opt.MapFrom((src, _) => src.OrTrnoVlddo))
                .ForMember(dest => dest.PesoACargar, opt => opt.MapFrom((src, _) => src.OrPsoACrgar))
                .ForMember(dest => dest.Concepto, opt => opt.MapFrom((src, _) => src.OrCncpto))
                .ForMember(dest => dest.CorrigeTurno, opt => opt.MapFrom((src, _) => src.OrCrrgeTrno))
                .ForMember(dest => dest.CorrigeTurnoFecha, opt => opt.MapFrom((src, _) => src.OrCrrgeTrnoFcha))
                .ForMember(dest => dest.ValidarVigenciaRadicaccion, opt => opt.MapFrom((src, _) => src.OrVldarVgnciaRdccion))
                .ForMember(dest => dest.FechaEntradaSociedad, opt => opt.MapFrom((src, _) => src.OrFchaEntrdaScdad))
                .ForMember(dest => dest.UsuarioEntradaSociedad, opt => opt.MapFrom((src, _) => src.OrUsrioEntrdaScdad))
                .ForMember(dest => dest.FechaPrimerLlamado, opt => opt.MapFrom((src, _) => src.OrFchaPrmerLlmdo))
                .ForMember(dest => dest.FechaUltimoLlamado, opt => opt.MapFrom((src, _) => src.OrFchaUltmoLlmdo))
                .ForMember(dest => dest.Tipo, opt => opt.MapFrom((src, _) => src.OrTpo))
                .ForMember(dest => dest.Tercero, opt => opt.MapFrom((src, _) => src.OrTrcro))
                .ForMember(dest => dest.TurnoNumero, opt => opt.MapFrom((src, _) => src.OrTrnoNmro))
                .ForMember(dest => dest.Observaciones, opt => opt.MapFrom((src, _) => src.OrObsrvcnes))
                .ForMember(dest => dest.Articulo, opt => opt.MapFrom((src, _) => src.OrArtclo))
                .ForMember(dest => dest.FechaSalidaSocidad, opt => opt.MapFrom((src, _) => src.OrFchaSldaScdad))
                .ForMember(dest => dest.UsuarioSalidaSociada, opt => opt.MapFrom((src, _) => src.OrUsrioSldaScdad))
                .ForMember(dest => dest.UbicacionRadicacion, opt => opt.MapFrom((src, _) => src.OrUbccionRdccion))
                .ForMember(dest => dest.TipoCarroceria, opt => opt.MapFrom((src, _) => src.OrTpoCrrcria))
                .ForMember(dest => dest.InterfazInside, opt => opt.MapFrom((src, _) => src.OrIntrfazInsde))
                .ForMember(dest => dest.InterfazInsideCancelada, opt => opt.MapFrom((src, _) => src.OrIntrfazInsdeCnclda))
                 .ForMember(dest => dest.CodigoCausalCancelacion, opt => opt.MapFrom((src, _) => src.OrCdgoCsalCnclcion)) 
                .ForMember(dest => dest.ObservacionesCancelacion, opt => opt.MapFrom((src, _) => src.OrObsrvcnesCnclcion))
                .ForMember(dest => dest.InterfazInsideConError, opt => opt.MapFrom((src, _) => src.OrIntrfazInsdeConError))
                .ForMember(dest => dest.InterfazInsideCanceladaConError, opt => opt.MapFrom((src, _) => src.OrIntrfazInsdeCncldaConError))
                .ForMember(dest => dest.IngresoIdInside, opt => opt.MapFrom((src, _) => src.OrIngrsoidInsde))
                .ForMember(dest => dest.IngresoId2Inside, opt => opt.MapFrom((src, _) => src.OrIngrsoid2Insde))
                .ForMember(dest => dest.IdCiudadNavegacion, opt => opt.MapFrom((src, _) => src.OrRowidCdadNavigation))
                .ForMember(dest => dest.IdConfiguracionVehicularNavegacion, opt => opt.MapFrom((src, _) => src.OrRowidCnfgrcionVhclarNavigation))
                .ForMember(dest => dest.IdDepositoNavegacion, opt => opt.MapFrom((src, _) => src.OrRowidDpstoNavigation))
                .ForMember(dest => dest.IdSolicitudRetiroNavegacion, opt => opt.MapFrom((src, _) => src.OrRowidSlctudRtroNavigation))
                .ForMember(dest => dest.IdTransportadoraNavegacion, opt => opt.MapFrom((src, _) => src.OrRowidTrnsprtdraNavigation))
                .ForMember(dest => dest.IdZonaCargueDescargueNavegacion, opt => opt.MapFrom((src, _) => src.OrRowidZnaCdNavigation));

            CreateMap<VwMdloRsrvaLstarDpsto, VwMdloRsrvaLstarDpstoDTO>()
              .ForMember(dest => dest.IdDeposito, opt => opt.MapFrom((src, _) => src.DeRowid))
              .ForMember(dest => dest.CodigoCompania, opt => opt.MapFrom((src, _) => src.DeCia))
              .ForMember(dest => dest.CodigoDeposito, opt => opt.MapFrom((src, _) => src.DeCdgo))
              .ForMember(dest => dest.EsSubdeposito, opt => opt.MapFrom((src, _) => src.DeEsSubdpsto))
              .ForMember(dest => dest.IdVisitaMotonave, opt => opt.MapFrom((src, _) => src.VmRowid));

            CreateMap<VwMdloRsrvaLstarVstaMtnve, VwMdloRsrvaLstarVstaMtnveDTO>()
            .ForMember(dest => dest.IdVisitaMotonave, opt => opt.MapFrom((src, _) => src.VmRowid))
            .ForMember(dest => dest.CodigoMotonave, opt => opt.MapFrom((src, _) => src.VmMotonaveCdgo))
            .ForMember(dest => dest.NombreMotonave, opt => opt.MapFrom((src, _) => src.VmMotonaveNmbre))
            .ForMember(dest => dest.Secuencia, opt => opt.MapFrom((src, _) => src.VmScncia))
            .ForMember(dest => dest.CodigoCompaniaVisitaMotonave, opt => opt.MapFrom((src, _) => src.VmCdgoCia));

            CreateMap<SpMdloRsrvaDtlleOrden, SpMdloRsrvaDtlleOrdenDTO>()
                .ForMember(dest => dest.CodigoOrden, opt => opt.MapFrom((src, _) => src.or_cdgo))
                .ForMember(dest => dest.IdentificacionConductorOrden, opt => opt.MapFrom((src, _) => src.or_idntfccion_cndctor))
                .ForMember(dest => dest.IdentificacionConductor, opt => opt.MapFrom((src, _) => src.cn_idntfccion))
                .ForMember(dest => dest.NombreConductor, opt => opt.MapFrom((src, _) => src.cn_nmbre))
                .ForMember(dest => dest.MovilConductor, opt => opt.MapFrom((src, _) => src.cn_mvil))
                .ForMember(dest => dest.TipoLicenciaConductor, opt => opt.MapFrom((src, _) => src.cn_tpo_lcncia))
                .ForMember(dest => dest.NumeroLicenciaConductor, opt => opt.MapFrom((src, _) => src.cn_nmro_lcncia))
                .ForMember(dest => dest.FechaVencimientoLicencia, opt => opt.MapFrom((src, _) => src.cn_fcha_vncmnto_lcncia))
                .ForMember(dest => dest.PlacaOrden, opt => opt.MapFrom((src, _) => src.or_plca))
                .ForMember(dest => dest.RemolqueOrden, opt => opt.MapFrom((src, _) => src.or_rmlque))
                .ForMember(dest => dest.IdConfiguracionVehicularOrden, opt => opt.MapFrom((src, _) => src.or_rowid_cnfgrcion_vhclar))
                .ForMember(dest => dest.IdConfiguracionVehicular, opt => opt.MapFrom((src, _) => src.cv_rowid))
                .ForMember(dest => dest.CodigoConfiguracionVehicular, opt => opt.MapFrom((src, _) => src.cv_cdgo))
                .ForMember(dest => dest.NombreConfiguracionVehicular, opt => opt.MapFrom((src, _) => src.cv_nmbre))
                .ForMember(dest => dest.PesoMaximoConfiguracionVehicular, opt => opt.MapFrom((src, _) => src.cv_pso_mxmo))
                .ForMember(dest => dest.ToleranciaConfiguracionVehicular, opt => opt.MapFrom((src, _) => src.cv_tlrncia))
                .ForMember(dest => dest.ManifiestoOrden, opt => opt.MapFrom((src, _) => src.or_mnfsto))
                .ForMember(dest => dest.RemisionOrden, opt => opt.MapFrom((src, _) => src.or_rmsion))
                .ForMember(dest => dest.PesoACargarOrden, opt => opt.MapFrom((src, _) => src.or_pso_a_crgar))
                .ForMember(dest => dest.IdCiudadOrden, opt => opt.MapFrom((src, _) => src.or_rowid_cdad))
                .ForMember(dest => dest.IdCiudad, opt => opt.MapFrom((src, _) => src.ci_rowid))
                .ForMember(dest => dest.CodigoCiudad, opt => opt.MapFrom((src, _) => src.ci_cdgo))
                .ForMember(dest => dest.NombreCiudad, opt => opt.MapFrom((src, _) => src.ci_nmbre))
                .ForMember(dest => dest.IdZonaCargueDescargueOrden, opt => opt.MapFrom((src, _) => src.or_rowid_zna_cd))
                .ForMember(dest => dest.IdZonaCargueDescargue, opt => opt.MapFrom((src, _) => src.zcd_rowid))
                .ForMember(dest => dest.CodigoZonaCargueDescargue, opt => opt.MapFrom((src, _) => src.zcd_cdgo))
                .ForMember(dest => dest.NombreZonaCargueDescargue, opt => opt.MapFrom((src, _) => src.zcd_nmbre))
                .ForMember(dest => dest.FechaLimiteSolicitudRetiro, opt => opt.MapFrom((src, _) => src.fcha_lmte_slctud_rtro))
                .ForMember(dest => dest.IdEmpaque, opt => opt.MapFrom((src, _) => src.em_rowid))
                .ForMember(dest => dest.CodigoEmpaque, opt => opt.MapFrom((src, _) => src.em_cdgo))
                .ForMember(dest => dest.NombreEmpaque, opt => opt.MapFrom((src, _) => src.em_nmbre))
                .ForMember(dest => dest.MinutosVigenciaReserva, opt => opt.MapFrom((src, _) => src.pa_mntos_vgnvia_rsrva))
                .ForMember(dest => dest.IdDeposito , opt => opt.MapFrom((src, _) => src.de_rowid))
                .ForMember(dest => dest.CodigoDeposito, opt => opt.MapFrom((src, _) => src.de_cdgo))
                .ForMember(dest => dest.IdVisitaMotonave, opt => opt.MapFrom((src, _) => src.vm_rowid))
                .ForMember(dest => dest.DescripcionVisitaMotonave, opt => opt.MapFrom((src, _) => src.vm_dscrpcion))
                .ForMember(dest => dest.IdTercero, opt => opt.MapFrom((src, _) => src.te_rowid))
                .ForMember(dest => dest.CodigoTercero, opt => opt.MapFrom((src, _) => src.te_cdgo))
                .ForMember(dest => dest.NombreTercero, opt => opt.MapFrom((src, _) => src.te_nmbre))
                .ForMember(dest => dest.CodigoProducto, opt => opt.MapFrom((src, _) => src.pr_cdgo))
                .ForMember(dest => dest.NombreProducto, opt => opt.MapFrom((src, _) => src.pr_nmbre))
                .ForMember(dest => dest.SaldoKilosDeposito, opt => opt.MapFrom((src, _) => src.sldo_klos_dpsto))
                .ForMember(dest => dest.SaldoUnidadesDeposito, opt => opt.MapFrom((src, _) => src.sldo_unddes_dpsto))
                .ForMember(dest => dest.CodigoSolicitudRetiro, opt => opt.MapFrom((src, _) => src.sr_cdgo))
                .ForMember(dest => dest.PlantaDestinoSolicitudRetiro, opt => opt.MapFrom((src, _) => src.sr_plnta_dstno))
                .ForMember(dest => dest.AutorizadoKilosSolicitudRetiro, opt => opt.MapFrom((src, _) => src.sr_autrzdo_klos))
                .ForMember(dest => dest.AutorizadoCantidadSolicitudRetiro, opt => opt.MapFrom((src, _) => src.sr_autrzdo_cntdad))
                .ForMember(dest => dest.LiberadoKilosSolicitudRetiro, opt => opt.MapFrom((src, _) => src.lbrdo_klos_slctud_rtro))
                .ForMember(dest => dest.LiberadoUnidadesSolicitudRetiro, opt => opt.MapFrom((src, _) => src.lbrdo_unddes_slctud_rtro))
                .ForMember(dest => dest.SaldoKilosSolicitudRetiro, opt => opt.MapFrom((src, _) => src.sldo_klos_slctud_rtro))
                .ForMember(dest => dest.SaldoUnidadesSolicitudRetiro, opt => opt.MapFrom((src, _) => src.sldo_unddes_slctud_rtro))
                .ForMember(dest => dest.TotalAutorizadoKilosTransportadora, opt => opt.MapFrom((src, _) => src.ttal_autrzdo_klos_trnsprtdra))
                .ForMember(dest => dest.TotalAutorizadoUnidadesTransportadora, opt => opt.MapFrom((src, _) => src.ttal_autrzdo_unddes_trnsprtdra))
                .ForMember(dest => dest.LiberadoKilosTransportadora, opt => opt.MapFrom((src, _) => src.lbrdo_klos_trnsprtdra))
                .ForMember(dest => dest.LiberadoUnidadesTransportadora, opt => opt.MapFrom((src, _) => src.lbrdo_unddes_trnsprtdra))
                .ForMember(dest => dest.RetiradoTransportadora, opt => opt.MapFrom((src, _) => src.rtrdo_trnsprtdra))
                .ForMember(dest => dest.SaldoKilosTransportadora, opt => opt.MapFrom((src, _) => src.sldo_klos_trnsprtdra))
                .ForMember(dest => dest.SaldoUnidadesTransportadora, opt => opt.MapFrom((src, _) => src.sldo_unddes_trnsprtdra))
                .ForMember(dest => dest.ReservaOrden, opt => opt.MapFrom((src, _) => src.or_rsrva))
                .ForMember(dest => dest.LlamadaOrden, opt => opt.MapFrom((src, _) => src.or_llmda))
                .ForMember(dest => dest.RadicadaOrden, opt => opt.MapFrom((src, _) => src.or_rdcda))
                .ForMember(dest => dest.TransitoOrden, opt => opt.MapFrom((src, _) => src.or_trnsto))
                .ForMember(dest => dest.FechaReservaOrden, opt => opt.MapFrom((src, _) => src.or_fcha_rsrva))
                .ForMember(dest => dest.FechaRegistroReservaOrden, opt => opt.MapFrom((src, _) => src.or_fcha_rgstro_rsrva))
                .ForMember(dest => dest.FechaPrimerLlamadoOrden, opt => opt.MapFrom((src, _) => src.or_fcha_prmer_llmdo))
                .ForMember(dest => dest.FechaUltimoLlamadoOrden, opt => opt.MapFrom((src, _) => src.or_fcha_ultmo_llmdo))
                .ForMember(dest => dest.FechaRadicacionOrden, opt => opt.MapFrom((src, _) => src.or_fcha_rdccion))
                .ForMember(dest => dest.FechaAnulacionOrden, opt => opt.MapFrom((src, _) => src.or_fcha_anlcion))
                .ForMember(dest => dest.ActivaOrden, opt => opt.MapFrom((src, _) => src.or_actva))
                .ForMember(dest => dest.ObservacionesOrden, opt => opt.MapFrom((src, _) => src.or_obsrvcnes));

            CreateMap<SpMdloRsrvaDtlleSlctudRtro, SpMdloRsrvaDtlleSlctudRtroDTO>()
                .ForMember(dest => dest.IdDeposito, opt => opt.MapFrom((src, _) => src.de_rowid))
                .ForMember(dest => dest.CodigoDeposito, opt => opt.MapFrom((src, _) => src.de_cdgo))
                .ForMember(dest => dest.IdVisitaMotonave, opt => opt.MapFrom((src, _) => src.vm_rowid))
                .ForMember(dest => dest.DescripcionVisitaMotonave, opt => opt.MapFrom((src, _) => src.vm_dscrpcion))
                .ForMember(dest => dest.IdTercero, opt => opt.MapFrom((src, _) => src.te_rowid))
                .ForMember(dest => dest.CodigoTercero, opt => opt.MapFrom((src, _) => src.te_cdgo))
                .ForMember(dest => dest.NombreTercero, opt => opt.MapFrom((src, _) => src.te_nmbre))
                .ForMember(dest => dest.CodigoProducto, opt => opt.MapFrom((src, _) => src.pr_cdgo))
                .ForMember(dest => dest.NombreProducto, opt => opt.MapFrom((src, _) => src.pr_nmbre))
                .ForMember(dest => dest.SaldoKilosDeposito, opt => opt.MapFrom((src, _) => src.sldo_klos_dpsto))
                .ForMember(dest => dest.SaldoUnidadesDeposito, opt => opt.MapFrom((src, _) => src.sldo_unddes_dpsto))
                .ForMember(dest => dest.CodigoSolicitudRetiro, opt => opt.MapFrom((src, _) => src.sr_cdgo))
                .ForMember(dest => dest.PlantaDestinoSolicitudRetiro, opt => opt.MapFrom((src, _) => src.sr_plnta_dstno))
                .ForMember(dest => dest.IdCiudad, opt => opt.MapFrom((src, _) => src.ci_rowid))
                .ForMember(dest => dest.CodigoCiudad, opt => opt.MapFrom((src, _) => src.ci_cdgo))
                .ForMember(dest => dest.NombreCiudad, opt => opt.MapFrom((src, _) => src.ci_nmbre))
                .ForMember(dest => dest.AutorizadoKilosSolicitudRetiro, opt => opt.MapFrom((src, _) => src.sr_autrzdo_klos))
                .ForMember(dest => dest.AutorizadoCantidadSolicitudRetiro, opt => opt.MapFrom((src, _) => src.sr_autrzdo_cntdad))
                .ForMember(dest => dest.LiberadoKilosSolicitudRetiro, opt => opt.MapFrom((src, _) => src.lbrdo_klos_slctud_rtro))
                .ForMember(dest => dest.LiberadoUnidadesSolicitudRetiro, opt => opt.MapFrom((src, _) => src.lbrdo_unddes_slctud_rtro))
                .ForMember(dest => dest.SaldoKilosSolicitudRetiro, opt => opt.MapFrom((src, _) => src.sldo_klos_slctud_rtro))
                .ForMember(dest => dest.SaldoUnidadesSolicitudRetiro, opt => opt.MapFrom((src, _) => src.sldo_unddes_slctud_rtro))
                .ForMember(dest => dest.TotalAutorizadoKilosTransportadora, opt => opt.MapFrom((src, _) => src.ttal_autrzdo_klos_trnsprtdra))
                .ForMember(dest => dest.TotalAutorizadoUnidadesTransportadora, opt => opt.MapFrom((src, _) => src.ttal_autrzdo_unddes_trnsprtdra))
                .ForMember(dest => dest.LiberadoKilosTransportadora, opt => opt.MapFrom((src, _) => src.lbrdo_klos_trnsprtdra))
                .ForMember(dest => dest.LiberadoUnidadesTransportadora, opt => opt.MapFrom((src, _) => src.lbrdo_unddes_trnsprtdra))
                .ForMember(dest => dest.RetiradoTransportadora, opt => opt.MapFrom((src, _) => src.rtrdo_trnsprtdra))
                .ForMember(dest => dest.SaldoKilosTransportadora, opt => opt.MapFrom((src, _) => src.sldo_klos_trnsprtdra))
                .ForMember(dest => dest.SaldoUnidadesTransportadora, opt => opt.MapFrom((src, _) => src.sldo_unddes_trnsprtdra));
        }
    }
}
